'use client';
import {useEffect,useMemo,useState} from 'react';

type Ex={name:string;method:string;reps:string}; type Day={day:string;short:string;focus:string;ex:Ex[]};
const days:Day[]=[
{day:'Monday',short:'MON',focus:'Chest + Triceps',ex:[{name:'Chest Press Machine',method:'HEAVY',reps:'12–15 reps'},{name:'DB Overhead Triceps Extension',method:'REPS',reps:'12–15 reps'},{name:'Incline Dumbbell Press',method:'5-5-5',reps:'5 right · 5 left · 5 together'},{name:'DB Skull Crusher',method:'REPS',reps:'12–15 reps'},{name:'Chest Machine',method:'60 SEC',reps:'Minimum 12 clean reps'},{name:'DB Triceps Kickback',method:'REPS',reps:'12–15 each arm'}]},
{day:'Tuesday',short:'TUE',focus:'Back + Biceps',ex:[{name:'Lat Pulldown',method:'60 SEC',reps:'Minimum 12 clean reps'},{name:'DB Hammer Curl',method:'5-5-5',reps:'5 right · 5 left · 5 together'},{name:'Seated Row',method:'HEAVY',reps:'12–15 reps'},{name:'DB Biceps Curl',method:'REPS',reps:'12–15 reps'},{name:'Biceps Curl Machine',method:'DROP',reps:'5 heavy · 5 medium · 5 light'},{name:'DB Pullover',method:'REPS',reps:'12–15 reps'}]},
{day:'Wednesday',short:'WED',focus:'Shoulders + Core',ex:[{name:'Shoulder Press Machine',method:'HEAVY',reps:'12–15 reps'},{name:'DB Shoulder Press',method:'5-5-5',reps:'5 right · 5 left · 5 together'},{name:'Rear Delt Fly Machine',method:'REPS',reps:'12–15 reps'},{name:'DB Lateral Raise',method:'5-5-5',reps:'5 right · 5 left · 5 together'},{name:'Ab Crunch Machine',method:'REPS',reps:'15–20 reps'},{name:'DB Front Raise',method:'REPS',reps:'12–15 reps'}]},
{day:'Thursday',short:'THU',focus:'Biceps + Triceps',ex:[{name:'Biceps Curl Machine',method:'DROP',reps:'5 heavy · 5 medium · 5 light'},{name:'DB Skull Crusher',method:'REPS',reps:'12–15 reps'},{name:'Triceps Machine / Cable',method:'HEAVY',reps:'12–15 reps'},{name:'DB Hammer Curl',method:'5-5-5',reps:'5 right · 5 left · 5 together'},{name:'Arm Machine',method:'60 SEC',reps:'Minimum 12 clean reps'},{name:'DB Curl / Extension',method:'REPS',reps:'12–15 reps'}]},
{day:'Friday',short:'FRI',focus:'Legs + Glutes',ex:[{name:'Leg Press',method:'HEAVY',reps:'12–15 reps'},{name:'DB Romanian Deadlift',method:'REPS',reps:'12–15 reps'},{name:'Leg Extension',method:'REPS',reps:'12–15 reps'},{name:'DB Split Squat',method:'10/10',reps:'10 right · 10 left'},{name:'Seated Leg Curl',method:'REPS',reps:'12–15 reps'},{name:'DB Goblet Squat',method:'REPS',reps:'12–15 reps'},{name:'Hip Abductor',method:'REPS',reps:'15–20 reps'},{name:'DB Calf Raise',method:'REPS',reps:'15–20 reps'}]}];
const key='animalx-v1';
export default function Home(){
 const js=new Date().getDay(); const initial=js>=1&&js<=5?js-1:0;
 const [tab,setTab]=useState<'today'|'week'|'history'>('today'); const [di,setDi]=useState(initial); const [data,setData]=useState<any>({}); const [timer,setTimer]=useState(60); const [running,setRunning]=useState(false);
 useEffect(()=>{try{setData(JSON.parse(localStorage.getItem(key)||'{}'))}catch{}},[]);
 useEffect(()=>{if(Object.keys(data).length)localStorage.setItem(key,JSON.stringify(data))},[data]);
 useEffect(()=>{if(!running)return; if(timer<=0){setRunning(false);navigator.vibrate?.(250);return} const x=setTimeout(()=>setTimer(t=>t-1),1000);return()=>clearTimeout(x)},[running,timer]);
 const d=days[di]; const done=(i:number)=>data?.[d.day]?.[i]?.done||[false,false,false]; const weight=(i:number)=>data?.[d.day]?.[i]?.weight||'';
 const upd=(i:number,v:any)=>setData((p:any)=>({...p,[d.day]:{...(p[d.day]||{}),[i]:{...(p[d.day]?.[i]||{}),...v}}}));
 const toggle=(i:number,r:number)=>{let a=[...done(i)];a[r]=!a[r];upd(i,{done:a})};
 const complete=useMemo(()=>d.ex.filter((_,i)=>done(i).every(Boolean)).length,[data,di]);
 return <main><header><div className="brand">AX</div><div><b>ANIMAL X</b><small>GYM TRACKER</small></div><div className="streak">{complete}/{d.ex.length}</div></header>
 <nav>{(['today','week','history'] as const).map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x.toUpperCase()}</button>)}</nav>
 {tab==='today'&&<><section className="hero"><div className="weekstrip">{days.map((x,i)=><button key={x.day} onClick={()=>setDi(i)} className={di===i?'sel':''}><span>{x.short}</span><i>{(data[x.day]&&x.ex.every((_,j)=>(data[x.day]?.[j]?.done||[]).every(Boolean)))?'✓':'○'}</i></button>)}</div><p>{d.day.toUpperCase()}</p><h1>{d.focus}</h1><div className="bar"><span style={{width:`${complete/d.ex.length*100}%`}}/></div><small>{complete} of {d.ex.length} exercises complete</small></section>
 <section className="cards">{d.ex.map((e,i)=><article key={e.name} className={done(i).every(Boolean)?'card completed':'card'}><div className="cardtop"><span className="num">{String(i+1).padStart(2,'0')}</span><span className="pill">{e.method}</span></div><h2>{e.name}</h2><p>{e.reps}</p><div className="weight"><label>WEIGHT <input inputMode="decimal" value={weight(i)} onChange={x=>upd(i,{weight:x.target.value})} placeholder="—"/> <b>lb</b></label></div><div className="rounds">{[0,1,2].map(r=><button onClick={()=>toggle(i,r)} className={done(i)[r]?'checked':''} key={r}>{done(i)[r]?'✓':r+1}</button>)}</div>{e.method==='60 SEC'&&<button className="timer" onClick={()=>{if(timer===0)setTimer(60);setRunning(!running)}}>{running?'PAUSE':'START'} · {timer}s</button>}</article>)}</section></>}
 {tab==='week'&&<section className="panel"><p>THIS WEEK</p><h1>5 Day Plan</h1>{days.map((x,i)=>{let n=x.ex.filter((_,j)=>(data[x.day]?.[j]?.done||[]).every(Boolean)).length;return <button className="weekrow" onClick={()=>{setDi(i);setTab('today')}} key={x.day}><b>{x.short}</b><span><strong>{x.focus}</strong><small>{n}/{x.ex.length} complete</small></span><em>{n===x.ex.length?'✓':'→'}</em></button>})}</section>}
 {tab==='history'&&<section className="panel"><p>PROGRESS</p><h1>Your weights</h1>{days.map(x=><div className="history" key={x.day}><b>{x.day} · {x.focus}</b>{x.ex.map((e,i)=><span key={e.name}>{e.name}<strong>{data[x.day]?.[i]?.weight||'—'} lb</strong></span>)}</div>)}</section>}
 </main>}
